(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Module constant_time.
  (*
  pub fn ct_select_u64(choice: u64, a: u64, b: u64) -> u64 {
      // choice = 0 -> mask = 0, choice = 1 -> mask = u64::MAX
      let mask = choice.wrapping_neg();
      b ^ (mask & (a ^ b))
  }
  *)
  Definition ct_select_u64 (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    match ε, τ, α with
    | [], [], [ choice; a; b ] =>
      ltac:(M.monadic
        (let choice := M.alloc (| Ty.path "u64", choice |) in
        let a := M.alloc (| Ty.path "u64", a |) in
        let b := M.alloc (| Ty.path "u64", b |) in
        M.read (|
          let~ mask : Ty.path "u64" :=
            M.call_closure (|
              Ty.path "u64",
              M.get_associated_function (| Ty.path "u64", "wrapping_neg", [], [] |),
              [ M.read (| choice |) ]
            |) in
          M.alloc (|
            Ty.path "u64",
            M.call_closure (|
              Ty.path "u64",
              BinOp.Wrap.bit_xor,
              [
                M.read (| b |);
                M.call_closure (|
                  Ty.path "u64",
                  BinOp.Wrap.bit_and,
                  [
                    M.read (| mask |);
                    M.call_closure (|
                      Ty.path "u64",
                      BinOp.Wrap.bit_xor,
                      [ M.read (| a |); M.read (| b |) ]
                    |)
                  ]
                |)
              ]
            |)
          |)
        |)))
    | _, _, _ => M.impossible "wrong number of arguments"
    end.
  
  Global Instance Instance_IsFunction_ct_select_u64 :
    M.IsFunction.C "plinko::constant_time::ct_select_u64" ct_select_u64.
  Admitted.
  Global Typeclasses Opaque ct_select_u64.
  
  (*
  pub fn ct_eq_u64(a: u64, b: u64) -> u64 {
      let diff = a ^ b;
      // If diff == 0, is_zero has high bit clear after this
      let is_zero = diff | diff.wrapping_neg();
      // High bit is 0 iff diff was 0; shift and invert
      1 ^ (is_zero >> 63)
  }
  *)
  Definition ct_eq_u64 (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    match ε, τ, α with
    | [], [], [ a; b ] =>
      ltac:(M.monadic
        (let a := M.alloc (| Ty.path "u64", a |) in
        let b := M.alloc (| Ty.path "u64", b |) in
        M.read (|
          let~ diff : Ty.path "u64" :=
            M.call_closure (|
              Ty.path "u64",
              BinOp.Wrap.bit_xor,
              [ M.read (| a |); M.read (| b |) ]
            |) in
          let~ is_zero : Ty.path "u64" :=
            M.call_closure (|
              Ty.path "u64",
              BinOp.Wrap.bit_or,
              [
                M.read (| diff |);
                M.call_closure (|
                  Ty.path "u64",
                  M.get_associated_function (| Ty.path "u64", "wrapping_neg", [], [] |),
                  [ M.read (| diff |) ]
                |)
              ]
            |) in
          M.alloc (|
            Ty.path "u64",
            M.call_closure (|
              Ty.path "u64",
              BinOp.Wrap.bit_xor,
              [
                Value.Integer IntegerKind.U64 1;
                M.call_closure (|
                  Ty.path "u64",
                  BinOp.Wrap.shr,
                  [ M.read (| is_zero |); Value.Integer IntegerKind.I32 63 ]
                |)
              ]
            |)
          |)
        |)))
    | _, _, _ => M.impossible "wrong number of arguments"
    end.
  
  Global Instance Instance_IsFunction_ct_eq_u64 :
    M.IsFunction.C "plinko::constant_time::ct_eq_u64" ct_eq_u64.
  Admitted.
  Global Typeclasses Opaque ct_eq_u64.
  
  (*
  pub fn ct_lt_u64(a: u64, b: u64) -> u64 {
      // Compute borrow bit of a - b
      let borrow = ((!a) & b) | (((!a) ^ b) & a.wrapping_sub(b));
      borrow >> 63
  }
  *)
  Definition ct_lt_u64 (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    match ε, τ, α with
    | [], [], [ a; b ] =>
      ltac:(M.monadic
        (let a := M.alloc (| Ty.path "u64", a |) in
        let b := M.alloc (| Ty.path "u64", b |) in
        M.read (|
          let~ borrow : Ty.path "u64" :=
            M.call_closure (|
              Ty.path "u64",
              BinOp.Wrap.bit_or,
              [
                M.call_closure (|
                  Ty.path "u64",
                  BinOp.Wrap.bit_and,
                  [ M.call_closure (| Ty.path "u64", UnOp.not, [ M.read (| a |) ] |); M.read (| b |)
                  ]
                |);
                M.call_closure (|
                  Ty.path "u64",
                  BinOp.Wrap.bit_and,
                  [
                    M.call_closure (|
                      Ty.path "u64",
                      BinOp.Wrap.bit_xor,
                      [
                        M.call_closure (| Ty.path "u64", UnOp.not, [ M.read (| a |) ] |);
                        M.read (| b |)
                      ]
                    |);
                    M.call_closure (|
                      Ty.path "u64",
                      M.get_associated_function (| Ty.path "u64", "wrapping_sub", [], [] |),
                      [ M.read (| a |); M.read (| b |) ]
                    |)
                  ]
                |)
              ]
            |) in
          M.alloc (|
            Ty.path "u64",
            M.call_closure (|
              Ty.path "u64",
              BinOp.Wrap.shr,
              [ M.read (| borrow |); Value.Integer IntegerKind.I32 63 ]
            |)
          |)
        |)))
    | _, _, _ => M.impossible "wrong number of arguments"
    end.
  
  Global Instance Instance_IsFunction_ct_lt_u64 :
    M.IsFunction.C "plinko::constant_time::ct_lt_u64" ct_lt_u64.
  Admitted.
  Global Typeclasses Opaque ct_lt_u64.
  
  (*
  pub fn ct_le_u64(a: u64, b: u64) -> u64 {
      1 ^ ct_lt_u64(b, a)
  }
  *)
  Definition ct_le_u64 (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    match ε, τ, α with
    | [], [], [ a; b ] =>
      ltac:(M.monadic
        (let a := M.alloc (| Ty.path "u64", a |) in
        let b := M.alloc (| Ty.path "u64", b |) in
        M.call_closure (|
          Ty.path "u64",
          BinOp.Wrap.bit_xor,
          [
            Value.Integer IntegerKind.U64 1;
            M.call_closure (|
              Ty.path "u64",
              M.get_function (| "plinko::constant_time::ct_lt_u64", [], [] |),
              [ M.read (| b |); M.read (| a |) ]
            |)
          ]
        |)))
    | _, _, _ => M.impossible "wrong number of arguments"
    end.
  
  Global Instance Instance_IsFunction_ct_le_u64 :
    M.IsFunction.C "plinko::constant_time::ct_le_u64" ct_le_u64.
  Admitted.
  Global Typeclasses Opaque ct_le_u64.
  
  (*
  pub fn ct_gt_u64(a: u64, b: u64) -> u64 {
      ct_lt_u64(b, a)
  }
  *)
  Definition ct_gt_u64 (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    match ε, τ, α with
    | [], [], [ a; b ] =>
      ltac:(M.monadic
        (let a := M.alloc (| Ty.path "u64", a |) in
        let b := M.alloc (| Ty.path "u64", b |) in
        M.call_closure (|
          Ty.path "u64",
          M.get_function (| "plinko::constant_time::ct_lt_u64", [], [] |),
          [ M.read (| b |); M.read (| a |) ]
        |)))
    | _, _, _ => M.impossible "wrong number of arguments"
    end.
  
  Global Instance Instance_IsFunction_ct_gt_u64 :
    M.IsFunction.C "plinko::constant_time::ct_gt_u64" ct_gt_u64.
  Admitted.
  Global Typeclasses Opaque ct_gt_u64.
End constant_time.
